### ISSUE TITLE
v13: formio_report_qweb PDF report qweb error.

### ISSUE THREAD

**Issue by walkerblackwell** [novacode-nl/odoo-formio#106]
I get t-value errors when attempting to print a PDF report of a form submission with Odoo 13 and most recent formio code pull.

See trace:

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_formio_report_qweb_component_not_implemented_1351
  File "/home/odoo/.local/lib/python3.6/site-packages/formiodata/components.py", line 39, in value
    return self.form['value']
KeyError: 'value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 2034, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/home/odoo/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1972, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 737, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/home/odoo/src/enterprise/web_studio/models/ir_actions_report.py", line 18, in render_qweb_html
    return super(IrActionsReport, self).render_qweb_html(docids, data)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 777, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 548, in render_template
    return view_obj.render_template(template, values)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 1191, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/odoo/src/odoo/addons/website/models/ir_ui_view.py", line 336, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 1199, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/odoo/src/enterprise/web_studio/models/ir_qweb.py", line 43, in render
    return super(IrQWeb, self).render(template, values=values, **options)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_formio_report_qweb_report_formio_form_1250
  File "<template>", line 2, in foreach_1249
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_formio_report_qweb_report_formio_form_document_1262
  File "<template>", line 2, in body_call_content_1260
  File "<template>", line 3, in body_call_content_1258
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_formio_report_qweb_report_formio_form_template_1278
  File "<template>", line 46, in foreach_1277
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_formio_report_qweb_component_1330
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_formio_report_qweb_panel_component_1337
  File "<template>", line 6, in foreach_1336
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_formio_report_qweb_component_1330
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_formio_report_qweb_tabs_component_1346
  File "<template>", line 5, in foreach_1345
  File "<template>", line 10, in foreach_1344
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_formio_report_qweb_component_1330
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 340, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'value'
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_formio_report_qweb_component_not_implemented_1351
  File "/home/odoo/.local/lib/python3.6/site-packages/formiodata/components.py", line 39, in value
    return self.form['value']
KeyError: 'value'

Error to render compiling AST
KeyError: 'value'
Template: formio_report_qweb.component_not_implemented
Path: /t/div/div[2]/t
Node: <t t-esc="component['_object'].value"/>

**Comment by bobslee** [comment]
Please check whether the `formio-data` PyPi library is on latest version.
Likewise pip upgrade: `pip3 install -U formio-data`

Awaiting for your answer.

**Comment by walkerblackwell** [comment]
updating now and will report back

**Comment by walkerblackwell** [comment]
Yep, it's most current, but same error.

best,
Walker

**Comment by bobslee** [comment]
The odd thing is, the KeyError raised on LOC below, doesn't match the upstream PyPi `formio-data` LOC line.

KeyError in trace, see LOC line 39
```
File "/home/odoo/.local/lib/python3.6/site-packages/formiodata/components.py", line 39, in value
return self.form['value']
KeyError: 'value'
```

However upstream LOC line:
https://github.com/novacode-nl/python-formio-data/blob/master/formiodata/components.py#L39

Please could you check/report?
`pip3 freeze | grep formio`

**Comment by walkerblackwell** [comment]
formio-data==0.1.0.dev12

**Comment by bobslee** [comment]
Or could you reproduce the error on my demo environment?
URL: demo13.novacode.nl/
Login: admin / admin

Maybe you could copy a part of the Form Builder schema, and reproduce the error?

**Comment by bobslee** [comment]
> formio-data==0.1.0.dev12

Gosh, you need `formio-data==0.1.0.dev17`
That's odd the upgrade didn't worked like expected.

**Comment by walkerblackwell** [comment]
I'll see if I can force it. odor.sh v13 platform . . .

**Comment by bobslee** [comment]
Aight ! I know... odoo.sh sometimes seems to be annoying ;)

**Comment by walkerblackwell** [comment]
Forced it to >=dev17 and now it's working. A note to any other odoo.sh users, that's what you'll want to do.

best,
Walker
