### ISSUE TITLE
Error template builder

### ISSUE THREAD

**Issue by fgauttron** [novacode-nl/odoo-formio#154]
Hello,

I installed the application on version 14 of odoo CE. When I open the form builder, I have an error and the builder does not open 
Thank you for your help.

Logs
Error: QWeb2: Template 'formio.builder' not found
    at Object.exception (https://intranet.cefim.eu/web/content/347-4e78d3e/web.assets_common.js:4383:7)
    at Engine._render (https://intranet.cefim.eu/web/content/347-4e78d3e/web.assets_common.js:4428:103)
    at Engine.render (https://intranet.cefim.eu/web/content/347-4e78d3e/web.assets_common.js:4424:151)
    at Class._renderView (https://intranet.cefim.eu/web/content/554-208733c/web.assets_backend.js:6478:357)
    at Class._render (https://intranet.cefim.eu/web/content/554-208733c/web.assets_backend.js:1274:330)
    at Class._render (https://intranet.cefim.eu/web/content/554-208733c/web.assets_backend.js:1679:222)
    at Class.prototype.<computed> [as _render] (https://intranet.cefim.eu/web/content/347-4e78d3e/web.assets_common.js:4621:488)
    at Class.start (https://intranet.cefim.eu/web/content/554-208733c/web.assets_backend.js:1274:25)
    at Class.prototype.<computed> [as start] (https://intranet.cefim.eu/web/content/347-4e78d3e/web.assets_common.js:4621:488)
    at https://intranet.cefim.eu/web/content/347-4e78d3e/web.assets_common.js:4957:52

**Comment by bobslee** [comment]
Hi @fgauttron ,
Please provide more info.

- Odoo server log (different error, warning?)
- Which version of the `formio` module ?
- Also additional module installed
- Which OS ? Debian, Ubuntu... ?

**Comment by fgauttron** [comment]
OS : Debian 10
Version 14 Formio https://apps.odoo.com/apps/modules/14.0/formio/
Another module installed : Form Partner https://apps.odoo.com/apps/modules/14.0/formio_partner/

Logs odoo:

2021-06-20 08:17:11,492 866 WARNING bitnami_odoo odoo.http: No CSRF validation token provided for path '/'

Odoo URLs are CSRF-protected by default (when accessed with unsafe
HTTP methods). See
https://www.odoo.com/documentation/14.0/developer/reference/http.html#csrf for
more details.

* if this endpoint is accessed through Odoo via py-QWeb form, embed a CSRF
  token in the form, Tokens are available via `request.csrf_token()`
  can be provided through a hidden input and must be POST-ed named
  `csrf_token` e.g. in your form add:

      <input type="hidden" name="csrf_token" t-att-value="request.csrf_token()"/>

* if the form is generated or posted in javascript, the token value is
  available as `csrf_token` on `web.core` and as the `csrf_token`
  value in the default js-qweb execution context

* if the form is accessed by an external third party (e.g. REST API
  endpoint, payment gateway callback) you will need to disable CSRF
  protection (and implement your own protection if necessary) by
  passing the `csrf=False` parameter to the `route` decorator.

2021-06-20 08:17:11,493 866 WARNING bitnami_odoo odoo.addons.http_routing.models.ir_http: 400 Bad Request:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-14.0.post20210530-py3.7.egg/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/bitnami/apps/odoo/lib/odoo-14.0.post20210530-py3.7.egg/odoo/http.py", line 804, in dispatch
    raise werkzeug.exceptions.BadRequest('Session expired (invalid CSRF token)')
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-14.0.post20210530-py3.7.egg/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/bitnami/apps/odoo/lib/odoo-14.0.post20210530-py3.7.egg/odoo/http.py", line 804, in dispatch
    raise werkzeug.exceptions.BadRequest('Session expired (invalid CSRF token)')

**Comment by bobslee** [comment]
This is really odd. 
I maintain several installations, also with customers, don't have this issue (with lastest version). 

Maybe it's related to something different?
