### ISSUE TITLE
formio_storage_filestore: submit of empty file components causes 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by frankvogler** [novacode-nl/odoo-formio#167]
**Reproduce:**
1) Create form with required and non-required file fields
2) submit form without uploading file to non-required fields

**Result:**
"Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/user/formio/formio/controllers/main.py", line 202, in form_submit
    form.write(vals)
  File "/home/odoo/src/odoo/addons/base_automation/models/base_automation.py", line 344, in write
    write.origin(records, vals, **kw)
  File "/home/odoo/src/user/formio/formio_storage_filestore/models/formio_form.py", line 21, in write
    self._process_storage_filestore_ir_attachments('write')
  File "/home/odoo/src/user/formio/formio_storage_filestore/models/formio_form.py", line 42, in _process_storage_filestore_ir_attachments
    for val in component.value:
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: 'NoneType' object is not iterable
"

**Comment by bobslee** [comment]
Hi @frankvogler , please could you test this issue with new version 0.9 of the `formio_storage_filestore` module.
Keep me posted.
