### ISSUE TITLE
incorrect use of safe_eval causes exception

### ISSUE THREAD

**Issue by MagnusKriel** [novacode-nl/odoo-formio#173]
https://github.com/novacode-nl/odoo-formio/blob/ddc4d4b55d8b43666c27272c22759747d973c1ee/formio_data_api/models/formio_form.py#L338

The above line should be safe_eval.safe_eval() else a 'module not callable' exception is thrown.
Same Issue further down. Total occurrences = 2

**Comment by bobslee** [comment]
Indeed, following error occurs.
I shall fix now (v14, v13).

```
  File "/home/odoo/odoo/addons/odoo-formio/formio/controllers/main.py", line 177, in form_submission
    etl_odoo_data = form.sudo()._etl_odoo_data()
  File "/home/odoo/odoo/addons/odoo-formio/formio_data_api/models/formio_form.py", line 230, in _etl_odoo_data
    value = self._etl_res_field_value(res_model_object, comp)
  File "/home/odoo/odoo/addons/odoo-formio/formio_data_api/models/formio_form.py", line 338, in _etl_res_field_value
    update = not self.filtered_domain(safe_eval(noupdate_form_domain))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: 'module' object is not callable
```

**Comment by bobslee** [comment]
@MagnusKriel thanks for the issue report!
Please could you test and respond whether solved?

**Comment by MagnusKriel** [comment]
@bobslee Thanks, I tested and is fixed now
